name: geat
description: Geat Publishing app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  appwrite: ^11.0.0
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1

  form_validator: ^2.1.1
  freezed_annotation: ^2.4.1

  image_picker: ^1.0.4
  intl: ^0.18.0
  json_annotation: ^4.8.1
  lottie: ^2.7.0
  markdown_editable_textinput: ^2.2.0
  markdown_widget: ^2.3.1
  motion_toast: ^2.7.9
  multi_select_flutter: ^4.1.3

  responsive_builder: ^0.7.0
  sliding_clipped_nav_bar: ^3.1.0+4

  timeago: ^3.6.0
  uuid: ^4.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.6

  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lottie/
    - assets/img/
  fonts:
    - family: Caveat
      fonts:
        - asset: assets/font/Caveat.ttf
    - family: GoudyBookletter
      fonts:
        - asset: assets/font/GoudyBookletter.ttf
    - family: IndieFlower
      fonts:
        - asset: assets/font/IndieFlower.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/font/RobotoMono.ttf
    - family: SourceCodePro
      fonts:
        - asset: assets/font/SourceCodePro.ttf
